### PR TITLE
Add aspect ratio and a new core option fba-neogeo-mode

### PR DESCRIPTION
**Pull request by AkimanBengus**

### CODE REVIEW

**Comment by fr500** [comment]
pretty cool

**Comment by barbudreadmon** [comment]
Nice work !

**Comment by AkimanBengus** [comment]
Thanks guys.

**Comment by Oggom** [comment]
Booting into AES causes some games (kof2000 for example) to trigger a copy protection warning which renders them unplayable. Standalone FBA doesn't seem to have this issue when switching over to AES.

**Comment by AkimanBengus** [comment]
I found another way to choose the bios.
Normally this method will fix the copy protection warning.
Do you know other games that have the same problem, I will test them with the new method?

**Comment by Oggom** [comment]
It can be reproduced with Matrimelee and Metal Slug 5 for example.

**Pull request merged**
