### PR TITLE
move descriptors to a different file

### PR DESCRIPTION
**Pull request by fr500**
implement descriptors for neogeo gamepad map, actually now that we have per-core/per-game remaps maybe we should have only ONE map per driver and implement
descriptors for other drivers so the user can use arcade or gamepad or newgen or whatever they want.

### CODE REVIEW

**Comment by fr500** [comment]
I guess I can add descriptors for neogeo arcade and neogeo newgen but imho mantaining 3 layouts now that we can do remapping is kind of pointless

**Comment by Oggom** [comment]
Having descriptors in a separate file is a good idea (libretro.cpp is getting quite ugly), however, which mapping present should stay?

Dropping arcade means people with arcade sticks (or keyboards I guess) would now have to re-map everything from scratch which is really unfitting for an arcade emulator while dropping the gamepad present means people with regular controllers have to spent their time mapping everything to their liking first.

Personally, I'm strongly supporting the arcade present for that matter. Having an arcade-system emulator with no out of the box support for arcade sticks just makes no sense to me.

If I didn't miscalculate anything we would need a total of 21 different descriptors to cover all games/drivers.

**Comment by fr500** [comment]
Ok, then let's have both, I'll make descriptors for CPS/NeoGeo in both modes

**Comment by barbudreadmon** [comment]
For whatever reason, your changes caused a segfault, so i undid your changes.

**Comment by fr500** [comment]
Odd this is working for me just fine in windows x64

**Comment by fr500** [comment]
Any particular game? I just tried neogeo maybe that's the reason

**Pull request merged**
