### PR TITLE
Implement another way to set the input descriptors to fit all games

### PR DESCRIPTION
**Pull request by AkimanBengus**
- This new implementation is based on the BurnInputInfo and normaly must
fit all games (not only CPS and neogeo).
The file descriptors.h is not needed anymore.
- Fix the diagnostic for NeoGeo that was not working. The diagnostic is
called Test in BurnInputInfo.
- Add another kind of diagnostics for Cave, Konami and others. Rem: For
cave games, long press to enter the diagnotic menu.
- Simplify the handling of the armwar, avsp and select neogeo button
exception.

### CODE REVIEW

**Comment by fr500** [comment]
did you test this?
I don't think it's gonna build, descriptors.h is still included

**Comment by fr500** [comment]
By the way great work! this is the best thing that could ever happen to the core! 
While many maps could still be problematic this makes input remapping great, thank you for this

**Comment by AkimanBengus** [comment]
Sorry, I forgot to remove the include in the same time than the file and I didn't rebuild :-(
I did the change and I will try a rebuild at noon to see if there is a build error.
Sorry again and thanks for the review.
Yes this is a great feature. Now we will see the correct input for each game :-)

**Comment by AkimanBengus** [comment]
I checked the compilation and it's ok now.

**Pull request merged**
