### PR TITLE
Added Classic Platform structure - ARMv7 Cortex A7 build

### PR DESCRIPTION
**Pull request by BananaRama203**

### CODE REVIEW

**Comment by barbudreadmon** [comment]
Are you sure all of this is needed ? Lots of things don't make any sense to me in there.

**Comment by barbudreadmon** [comment]
Clean your commit from unwanted stuff if you want it to be merged. As far as i understand, that new rule is not even needed, this is just some standard "armv7-neon-hf" device.

**Comment by joolswills** [comment]
Doesn't this break anyone using platform=armv etc? Doesn't look correct to me

**Comment by joolswills** [comment]
(the override platform will not get set).

**Comment by joolswills** [comment]
Ah my bad. It's not set if classic is included. Misread nasty makefile logic :-)

**Pull request merged**
