### PR TITLE
Android build fix

### PR DESCRIPTION
**Pull request by fr500**
Sending in behalf of @diablodiab, it should be fine
I guess I need the standalone toolchain to get this to build, I'll test once it's merged

### CODE REVIEW

**Comment by diablodiab** [comment]
Did you run into problems compiling it?

**Comment by diablodiab** [comment]
The hacks I did were without any consideration for other builds, I just wanted it to compile. It was pulled a little too quickly into the main repo, see #74 :)

I think this commit should be reverted and the fixes should be implemented in a way that only effects Android. The commit on my own repo was just for info and so that we could find a good way to adjust for it.

**Comment by fr500** [comment]
Yeah don't worry if it's problematic I'll revert it it's no big deal if a core doesn't build one day.
I had problems yes, were you using a generic linux arm-eabi compiler?

I was trying to build with the standalone toolchain and I get this:

```
arm-linux-androideabi-gcc -DARM -O3 -DNDEBUG -fPIC -Wno-write-strings -DUSE_SPEEDHACKS -D__LIBRETRO__ -D__LIBRETRO_OPTIMIZATIONS__ -DWANT_NEOGEOCD -DLSB_FIRST -marm -DANDROID -Dlog2\(x\)=\(log\(x\)/1.4426950408889634\) -DINLINE="static inline" -DSH2_INLINE="static inline" -D__LIBRETRO_OPTIMIZATIONS__   -DFRONTEND_SUPPORTS_RGB565 -Isrc/burner/win32 -Isrc/burner/libretro -Isrc/burner/libretro/tchar -Isrc/burn -Isrc/cpu -Isrc/burn/snd -Isrc/burn/devices -Isrc/intf -Isrc/intf/input -Isrc/intf/cd -Isrc/intf/audio -Isrc/burner -Isrc/cpu -Isrc/cpu/i8039 -Isrc/dep/libs/zlib -Isrc/burn/drv/capcom -Isrc/burn/drv/konami -Isrc/burn/drv/dataeast -Isrc/burn/drv/cave -Isrc/burn/drv/neogeo -Isrc/burn/drv/psikyo -Isrc/burn/drv/sega -Isrc/burn/drv/toaplan -Isrc/burn/drv/taito -Isrc/dep/generated -Isrc/dep/libs -c src/burner/ioapi.c -o src/burner/ioapi.o
arm-linux-androideabi-gcc -DARM -O3 -DNDEBUG -fPIC -Wno-write-strings -DUSE_SPEEDHACKS -D__LIBRETRO__ -D__LIBRETRO_OPTIMIZATIONS__ -DWANT_NEOGEOCD -DLSB_FIRST -marm -DANDROID -Dlog2\(x\)=\(log\(x\)/1.4426950408889634\) -DINLINE="static inline" -DSH2_INLINE="static inline" -D__LIBRETRO_OPTIMIZATIONS__   -DFRONTEND_SUPPORTS_RGB565 -Isrc/burner/win32 -Isrc/burner/libretro -Isrc/burner/libretro/tchar -Isrc/burn -Isrc/cpu -Isrc/burn/snd -Isrc/burn/devices -Isrc/intf -Isrc/intf/input -Isrc/intf/cd -Isrc/intf/audio -Isrc/burner -Isrc/cpu -Isrc/cpu/i8039 -Isrc/dep/libs/zlib -Isrc/burn/drv/capcom -Isrc/burn/drv/konami -Isrc/burn/drv/dataeast -Isrc/burn/drv/cave -Isrc/burn/drv/neogeo -Isrc/burn/drv/psikyo -Isrc/burn/drv/sega -Isrc/burn/drv/toaplan -Isrc/burn/drv/taito -Isrc/dep/generated -Isrc/dep/libs -c src/burner/unzip.c -o src/burner/unzip.o
arm-linux-androideabi-gcc -DARM -O3 -DNDEBUG -fPIC -Wno-write-strings -DUSE_SPEEDHACKS -D__LIBRETRO__ -D__LIBRETRO_OPTIMIZATIONS__ -DWANT_NEOGEOCD -DLSB_FIRST -marm -DANDROID -Dlog2\(x\)=\(log\(x\)/1.4426950408889634\) -DINLINE="static inline" -DSH2_INLINE="static inline" -D__LIBRETRO_OPTIMIZATIONS__   -DFRONTEND_SUPPORTS_RGB565 -Isrc/burner/win32 -Isrc/burner/libretro -Isrc/burner/libretro/tchar -Isrc/burn -Isrc/cpu -Isrc/burn/snd -Isrc/burn/devices -Isrc/intf -Isrc/intf/input -Isrc/intf/cd -Isrc/intf/audio -Isrc/burner -Isrc/cpu -Isrc/cpu/i8039 -Isrc/dep/libs/zlib -Isrc/burn/drv/capcom -Isrc/burn/drv/konami -Isrc/burn/drv/dataeast -Isrc/burn/drv/cave -Isrc/burn/drv/neogeo -Isrc/burn/drv/psikyo -Isrc/burn/drv/sega -Isrc/burn/drv/toaplan -Isrc/burn/drv/taito -Isrc/dep/generated -Isrc/dep/libs -c src/burn/snd/ay8910.c -o src/burn/snd/ay8910.o
<command-line>:0:16: error: expected ')' before '/' token
make: *** [src/burn/snd/ay8910.o] Error 1
make: *** Waiting for unfinished jobs....
cp: cannot stat ‘fba_libretro_android.so’: No such file or directory
```

**Comment by fr500** [comment]
I think it doesn't like something in the log function and it's parsing some symbol as a escape sequence.
Have you ever used the standalone toolchain? I'm not really good at tweaking makefiles but I can surely help you to setup the standalone toolchain and fixing this properly

**Comment by diablodiab** [comment]
I was thinking of looking into creating a JNI makefile instead. Do I understand it correctly, that it would make things easier for the buildbot?

**Comment by fr500** [comment]
Yes jni makefiles work better and one makefile works for all the ABIS

**Pull request merged**
