### PR TITLE
Add macros input in core options depending on the game/system

### PR DESCRIPTION
**Pull request by AkimanBengus**
FBA handles some macros input for certain games/systems.
Street Fighter like games: 3x Punch and 3x Kick
Neogeo: AB, BC, CD ...
PGM: Button 12, 23, 123 ...

It's now possible to choose the macro you want to activate via the core
options.
For Street Fighter only the L2, L3, R2 and R3 buttons will be available.
For the others all the L and R buttons are free to use.
By default, all the macros are set on 'None'.
When you choose a button for a macro, this macro will be activated and
will also appear in the 'Core Input Remapping Options'
The macro core options are affected by game to be able to configure
different macro for each game.

### CODE REVIEW

**Comment by fr500** [comment]
Why the core options though?
Maybe just enable/disable macros in core options would be better, then add the buttons to the map and to the descriptors.

I will give this a shoot once it builds

**Comment by AkimanBengus** [comment]
Because this is technically not possible to assign all macros input to the RetroPad.

For Street Fighter games like, it would be possible because there are only 2 macros but for NeoGeo and Pgm there are 11 macros and it remains only 6 buttons from the RetroPad (all L and R)
And the other reason is because each game has his own needs (for example kof95 needs mainly AB, CD and ABC while Last Blade needs only AB)
With this system you can choose exactly the macros you want for the each game.

**Comment by fr500** [comment]
yeah you're right.
btw eeprom saving for CPS2 is not working anymore... can you take a look?
I tried to fix it like the last time but it's not working.

**Comment by fr500** [comment]
nvm found the issue, will send a PR soon

**Pull request merged**
